####Mikhail Lemaev#######
From centos:latest
Label maintainer ="lemaevmikhail@gmail.com"
Run yum update -y
Run yum install python3 -y
Copy script.py  /home/script.py
WORKDIR /home
CMD ["python3", "/home/script.py"]
